Helper Function for Signature checks
CityOfZion/neon-js pull request #606
Opened 2020-10-12 05:33 UTC by kjlevitz

Created helper function to check signatures (single and multi)
Created test driver to test signature helper function

2020-10-16 07:23 UTC, ixje commented
@snowypowers I see that the linting for this PR passes, but at the same time I see quite some inconsistency in the code style used. The following cases are all in there
```
if(something){
if (something){
if ( something){
if (something) {
```

I see `prettier` in the `eslintrc`. Shouldn't that have caught these "error"?

2020-10-16 07:50 UTC, ixje requested changes

2020-10-16 07:50 UTC, ixje commented on helpers/signatureVerification.ts
> +    const PUSHDATA1   = 12, //0x0C
We can use the `OpCode` constants from `import { OpCode } from "../sc";`

2020-10-16 07:50 UTC, ixje commented on helpers/signatureVerification.ts
> +*/
Try to follow the existing documentation style using 
```
/**
 * description
 */
```
```suggestion
/**
 * Check if the format of input matches that of a single signature contract
 */
```

2020-10-16 07:50 UTC, ixje commented on helpers/signatureVerification.ts
> + }
this can be removed based on https://github.com/CityOfZion/neon-js/issues/591#issuecomment-707607923

2020-10-16 07:50 UTC, ixje commented on helpers/signatureVerification.ts
> +export function isSignatureContract(signature_script){
add type for input and function return

2020-10-16 07:50 UTC, ixje commented on helpers/signatureVerification.ts
> +export function isMultisigContract(signatureScript, state?: SignParamsLike){
add type for input and return

2020-10-16 07:50 UTC, ixje commented on helpers/signatureVerification.ts
> +    const PUSHINT8 = 12, //0 //0x00
same as for `isSignatureContract`, re-use the existing `OpCode` constants

2020-10-16 07:50 UTC, ixje commented on helpers/signatureVerification.ts
> +*/
same comment as for the single contract version

2020-10-16 07:50 UTC, ixje commented on helpers/signatureVerification.ts
> +    */
remove comment

2020-10-16 07:50 UTC, ixje commented on helpers/signatureVerification.ts
> +*/
Remove comments as this should not end up in production code

2020-10-16 07:50 UTC, ixje commented on packages/neon-api/package-lock.json
> +{
this seems like a temporary file based on your setup. I don't think this should be added

2020-10-16 07:50 UTC, ixje commented on packages/neon-core/src/wallet/Account.ts
> +//import { InteropServiceCode } from "../sc";
remove comment

2020-10-16 07:50 UTC, ixje commented on helpers/signatureVerification.ts
> +/*
Please apply all comments on the functions in this file to the version in `misc.ts` and then delete this file. We don't need the functions in 2 places

2020-10-19 05:24 UTC, snowypowers commented
> @snowypowers I see that the linting for this PR passes, but at the same time I see quite some inconsistency in the code style used. The following cases are all in there
> 
> ```
> if(something){
> if (something){
> if ( something){
> if (something) {
> ```
> 
> I see `prettier` in the `eslintrc`. Shouldn't that have caught these "error"?

The lint rule only runs on modified files within `packages` folder. 

`helpers` folder is for runnable helpers for administrative purposes. Please move all publishable code into packages.

2020-10-19 12:49 UTC, closed without merging